# Generated by Django 5.2.5 on 2025-08-12 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("retail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="employees",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Сотрудник"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="products",
            field=models.ManyToManyField(
                related_name="network_nodes",
                to="retail.product",
                verbose_name="Доступные продукты",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="retail.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
